// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATguLCKy5uKxVSJBSJvZm7y3dNjZZOlO8',
    appId: '1:417194924834:web:9ce8683cd2c4bf7033237b',
    messagingSenderId: '417194924834',
    projectId: 'ice-student-management-75594',
    authDomain: 'ice-student-management-75594.firebaseapp.com',
    storageBucket: 'ice-student-management-75594.firebasestorage.app',
    measurementId: 'G-2M8ZWZKFZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oVme2VbCXifxmY_jbbkThupV859Epcw',
    appId: '1:417194924834:android:6b9ac2ec96fba52c33237b',
    messagingSenderId: '417194924834',
    projectId: 'ice-student-management-75594',
    storageBucket: 'ice-student-management-75594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-uvFGjFpfmMueLtw7R1kNRUcazC6iig',
    appId: '1:417194924834:ios:5aa45aab142422b433237b',
    messagingSenderId: '417194924834',
    projectId: 'ice-student-management-75594',
    storageBucket: 'ice-student-management-75594.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-uvFGjFpfmMueLtw7R1kNRUcazC6iig',
    appId: '1:417194924834:ios:5aa45aab142422b433237b',
    messagingSenderId: '417194924834',
    projectId: 'ice-student-management-75594',
    storageBucket: 'ice-student-management-75594.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATguLCKy5uKxVSJBSJvZm7y3dNjZZOlO8',
    appId: '1:417194924834:web:4b63e598753dce8133237b',
    messagingSenderId: '417194924834',
    projectId: 'ice-student-management-75594',
    authDomain: 'ice-student-management-75594.firebaseapp.com',
    storageBucket: 'ice-student-management-75594.firebasestorage.app',
    measurementId: 'G-WY40B7NYHG',
  );

}